
PAGEID = 42465
TITLE = 'Basilique du Sacré-Cœur de Montmartre'

fake_data = {'batchcomplete': '',
 'query': {'geosearch': [{'dist': 26.4,
                          'lat': 48.88694,
                          'lon': 2.34306,
                          'ns': 0,
                          'pageid': PAGEID,
                          'primary': '',
                          'title': TITLE},
                         {'dist': 41.4,
                          'lat': 48.8863361,
                          'lon': 2.3431833,
                          'ns': 0,
                          'pageid': 5475519,
                          'primary': '',
                          'title': "Statue équestre de Jeanne d'Arc (Basilique "
                                   'du Sacré-Cœur de Montmartre)'},
                         {'dist': 42.9,
                          'lat': 48.886536,
                          'lon': 2.342577,
                          'ns': 0,
                          'pageid': 5422747,
                          'primary': '',
                          'title': 'Rue du Cardinal-Guibert'},
                         {'dist': 67.3,
                          'lat': 48.8861,
                          'lon': 2.34306,
                          'ns': 0,
                          'pageid': 24951,
                          'primary': '',
                          'title': 'Montmartre'},
                         {'dist': 76.4,
                          'lat': 48.88736,
                          'lon': 2.34279,
                          'ns': 0,
                          'pageid': 11093773,
                          'primary': '',
                          'title': 'Carmel de Montmartre'},
                         {'dist': 78.8,
                          'lat': 48.886667,
                          'lon': 2.342028,
                          'ns': 0,
                          'pageid': 214610,
                          'primary': '',
                          'title': 'Église Saint-Pierre de Montmartre'},
                         {'dist': 91,
                          'lat': 48.885898,
                          'lon': 2.343317,
                          'ns': 0,
                          'pageid': 5422745,
                          'primary': '',
                          'title': 'Rue du Cardinal-Dubois'},
                         {'dist': 96.7,
                          'lat': 48.8868,
                          'lon': 2.34179,
                          'ns': 0,
                          'pageid': 3055503,
                          'primary': '',
                          'title': 'Cimetière du Calvaire'},
                         {'dist': 97.9,
                          'lat': 48.887409,
                          'lon': 2.342301,
                          'ns': 0,
                          'pageid': 5425013,
                          'primary': '',
                          'title': 'Cité du Sacré-Cœur'},
                         {'dist': 106.7,
                          'lat': 48.88606,
                          'lon': 2.342024,
                          'ns': 0,
                          'pageid': 5422579,
                          'primary': '',
                          'title': 'Rue Azaïs'}]}}
